# Generated by Django 2.2.1 on 2019-06-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=800)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('appointment_on', models.DateTimeField()),
            ],
        ),
    ]
